example.adoc: example.tex Makefile
	pandoc                 \
		--standalone       \
		--from latex       \
		--to asciidoctor   \
		--metadata-file=metadata.yml \
		example.tex

# Note going to work for enough of our options
