= README
Kahlil Hodgson <kahlil.hodgson999@gmail.com>
2019-08-28

Searching for an optimal toolchain for publishing a books containing mathematical
equations (STEM).

== Goals:

Want to be able to easily maintain and produce high-quality output for both printing and
online consumption.

By "high-quality" we mean both attractive and functional. Mathematical formula's and
layout should be clear and attractive. Navigation should be supported (contents pages).
Cross-referencing should be complete and hyper-linking should work.

For printing this will mean PDF, though this should include DocBook for publishing with
O'Reilly.

Do we want to support generating multi-page HTML5?

Do we want to support authoring with multi-file documents?

== Formats

=== LaTeX

This is a complex and feature-rich document processing language.
Supports text based editing, but can be complicated.
Huge STEM support.
A bit old fashioned.
Complex for simple documents.
A bit ungainly.

Want to support this as an input/authoring language.
Perhaps via translation to AsciiDoc or DocBook5.

=== AsciiDoc

This is a plain text markup language.
Simple but very complete feature set.
Supports LaTeX maths and AsciiMath via MathJax.
Functionally equivalent to DocBook5.
Supported by GitHub documents.

Want to support this as an input/authoring language.

=== DocBook5

This is an OASIS standard.
It is used by many publishing firms including O'Reilly.
We should support it as an output format.

It is an XML format which is challenging for human composition--though there are tools
to help with this.

Want to avoid this as authoring format.
May use it as an intermediate format.

=== PDF

Universal printing and electronic display format.

Want to support this as a secondary output format. Should be able to get here from
DocBook.

=== HTML5

This is the dominant modern web-publishing format.

Want to support this as a primary output format

Multi-page?


== Tools

`hevea`::
Good LaTeX to HTML conversion (multi-page). However, maths output is not very attractive,
neither is the HTML (very particularly modern).

`asciidoctor`::

`plastex`::
???



== Experiments

=== `pdflatex`::

Standard tool for generating PDF output from LaTeX.

=== `lwarp`


Got this to work and the output looked pretty good. However could not control the HTML
output as well as I would have liked.  Could not find an easy way to get extra content
into the HTML--like sidebars and wrappers.

Difficult to extend and modify. Web output is more modern than `hevea`.

Supported by a single developer. Not on GitHub.

=== `plastex`

Can generate DocBook and HTML from LaTeX.

DocBook is good but HTML output is very old fashioned.

Does not work with Python 3 yet.

=== `pandoc`

Can use this to generate DocBook, AsciiDoc, and HTML from LaTex.

==== LaTeX -> DocBook5


==== LaTeX -> HTML

Looks OK, but could not get the MathJax format to load. Apparently --mathjax and
standalone do not work together.

==== LaTeX -> AsciiDoc

Pretty good conversion. Had to remove some `section` redefinitions to make this work
though.

=== `xsltproc`

Standard XML translation tool. Used to reformat DocBook.

Used this to unpack DocBook5 to multi-page (chunked) HTML.

Output still looks very old fashioned out of the box. Have the feeling that this is not
going to be the best approach.

=== AsciiDoc

This is a great format and the tool produces very nice HTML5 output. Very easy to style.

Good modern tool. Under active development Supported by GitHub and O'Reilly.

Need to review the experimental multi-page output filter.

This was the most successful so I delved deep.

==== Outstanding issues

Numbering Figures::

Currently we cannot figures to number chapter-wise, e.g., "Figure 3.4". Upstream is
working on this, but I think the fix depends on another large change in the codebase.
See https://github.com/asciidoctor/asciidoctor/issues/979.

User-defined Environments::

Common numbered environments in maths ("theorem", "lemma", "corollary", "exercise") do
not have a clear expression in AsciiDoc. This ties in with the section numbering issues
detailed elsewhere.

Multi-page HTML output::

There is experimental support for this. Just waiting on key developer to get some more
time: https://github.com/asciidoctor/asciidoctor-extensions-lab/blob/master/lib/multipage-html5-converter.rb
